CREATE TABLE DATABASE(
DISTRICT NUMBER,
DISTRICTNAME VARCHAR2(50),
CAMPUS NUMBER,
CAMPUSNAME VARCHAR2(50),
REGION NUMBER,
COUNTY NUMBER,
COUNTYNAME VARCHAR2(50),
TYPE VARCHAR2(50),
GRADES VARCHAR2(50),
RATING VARCHAR2(50),
HOURS11 NUMBER,
HOURS12 NUMBER,
HOURS13 NUMBER,
ITEMS1 NUMBER,
ITEMS2 NUMBER,
ITEMS3 NUMBER
);